// <auto-generated />
using System;
using Andy.Containers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Andy.Containers.Infrastructure.Migrations
{
    [DbContext(typeof(ContainersDbContext))]
    [Migration("20260420232544_AddRuns")]
    partial class AddRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Andy.Containers.Messaging.OutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Subject");

                    b.HasIndex("PublishedAt", "CreatedAt");

                    b.ToTable("OutboxEntries");
                });

            modelBuilder.Entity("Andy.Containers.Models.ApiKeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("ChangeHistory")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnvVarName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedValue")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Provider", "Label")
                        .IsUnique();

                    b.ToTable("ApiKeyCredentials");
                });

            modelBuilder.Entity("Andy.Containers.Models.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllocatedResources")
                        .HasColumnType("jsonb");

                    b.Property<string>("ClientInfo")
                        .HasColumnType("text");

                    b.Property<string>("CodeAssistant")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContainerUser")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreationSource")
                        .HasColumnType("integer");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("GitRepository")
                        .HasColumnType("jsonb");

                    b.Property<string>("HostIp")
                        .HasColumnType("text");

                    b.Property<string>("IdeEndpoint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkConfig")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("VncEndpoint")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerGitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CloneCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CloneDepth")
                        .HasColumnType("integer");

                    b.Property<string>("CloneError")
                        .HasColumnType("text");

                    b.Property<string>("CloneMetadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CloneStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CloneStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialRef")
                        .HasColumnType("text");

                    b.Property<bool>("IsFromTemplate")
                        .HasColumnType("boolean");

                    b.Property<bool>("Submodules")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CloneStatus");

                    b.HasIndex("ContainerId");

                    b.ToTable("ContainerGitRepositories");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseImageDigest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BuildCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BuildLog")
                        .HasColumnType("text");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BuildStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BuildStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("BuiltOffline")
                        .HasColumnType("boolean");

                    b.Property<string>("Changelog")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DependencyLock")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DependencyManifest")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ImageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviousImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PreviousImageId");

                    b.HasIndex("Tag");

                    b.HasIndex("TemplateId", "OrganizationId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CatalogScope")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeAssistant")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultResources")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("jsonb");

                    b.Property<string>("GitRepositories")
                        .HasColumnType("jsonb");

                    b.Property<bool>("GpuPreferred")
                        .HasColumnType("boolean");

                    b.Property<bool>("GpuRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("GuiType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdeType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ports")
                        .HasColumnType("jsonb");

                    b.Property<string>("Scripts")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Toolchains")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogScope");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentTemplateId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Andy.Containers.Models.DependencySpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("Ecosystem")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatePolicy")
                        .HasColumnType("integer");

                    b.Property<string>("VersionConstraint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Name")
                        .IsUnique();

                    b.ToTable("DependencySpecs");
                });

            modelBuilder.Entity("Andy.Containers.Models.GitCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CredentialType")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHost")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Label")
                        .IsUnique();

                    b.ToTable("GitCredentials");
                });

            modelBuilder.Entity("Andy.Containers.Models.ImageBuildRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Architecture")
                        .HasColumnType("text");

                    b.Property<string>("BuildLog")
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerfileChecksum")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImageCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageDigest")
                        .HasColumnType("text");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ImageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("LastBuildError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastBuiltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("Os")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageReference");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("ImageBuildRecords");
                });

            modelBuilder.Entity("Andy.Containers.Models.InfrastructureProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Capabilities")
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionConfig")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Andy.Containers.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Andy.Containers.Models.ResolvedDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactHash")
                        .HasColumnType("text");

                    b.Property<long?>("ArtifactSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DependencySpecId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FromOfflineCache")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DependencySpecId");

                    b.HasIndex("ImageId");

                    b.ToTable("ResolvedDependencies");
                });

            modelBuilder.Entity("Andy.Containers.Models.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("AgentRevision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvironmentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Status");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Andy.Containers.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Andy.Containers.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefaultContainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GitBranch")
                        .HasColumnType("text");

                    b.Property<string>("GitRepositories")
                        .HasColumnType("jsonb");

                    b.Property<string>("GitRepositoryUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultContainerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("ContainerWorkspace", b =>
                {
                    b.Property<Guid>("ContainersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ContainersId", "WorkspaceId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ContainerWorkspace");
                });

            modelBuilder.Entity("Andy.Containers.Models.Container", b =>
                {
                    b.HasOne("Andy.Containers.Models.InfrastructureProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Andy.Containers.Models.ContainerTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerEvent", b =>
                {
                    b.HasOne("Andy.Containers.Models.Container", "Container")
                        .WithMany("Events")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerGitRepository", b =>
                {
                    b.HasOne("Andy.Containers.Models.Container", "Container")
                        .WithMany("GitRepositories")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerImage", b =>
                {
                    b.HasOne("Andy.Containers.Models.ContainerImage", "PreviousImage")
                        .WithMany()
                        .HasForeignKey("PreviousImageId");

                    b.HasOne("Andy.Containers.Models.ContainerTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreviousImage");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerSession", b =>
                {
                    b.HasOne("Andy.Containers.Models.Container", "Container")
                        .WithMany("Sessions")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Andy.Containers.Models.ContainerTemplate", b =>
                {
                    b.HasOne("Andy.Containers.Models.ContainerTemplate", "ParentTemplate")
                        .WithMany()
                        .HasForeignKey("ParentTemplateId");

                    b.Navigation("ParentTemplate");
                });

            modelBuilder.Entity("Andy.Containers.Models.DependencySpec", b =>
                {
                    b.HasOne("Andy.Containers.Models.ContainerTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Andy.Containers.Models.ResolvedDependency", b =>
                {
                    b.HasOne("Andy.Containers.Models.DependencySpec", "DependencySpec")
                        .WithMany()
                        .HasForeignKey("DependencySpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Andy.Containers.Models.ContainerImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependencySpec");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Andy.Containers.Models.Run", b =>
                {
                    b.OwnsOne("Andy.Containers.Models.WorkspaceRef", "WorkspaceRef", b1 =>
                        {
                            b1.Property<Guid>("RunId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Branch")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("WorkspaceRef_Branch");

                            b1.Property<Guid>("WorkspaceId")
                                .HasColumnType("uuid")
                                .HasColumnName("WorkspaceRef_WorkspaceId");

                            b1.HasKey("RunId");

                            b1.ToTable("Runs");

                            b1.WithOwner()
                                .HasForeignKey("RunId");
                        });

                    b.Navigation("WorkspaceRef")
                        .IsRequired();
                });

            modelBuilder.Entity("Andy.Containers.Models.Team", b =>
                {
                    b.HasOne("Andy.Containers.Models.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Andy.Containers.Models.Workspace", b =>
                {
                    b.HasOne("Andy.Containers.Models.Container", "DefaultContainer")
                        .WithMany()
                        .HasForeignKey("DefaultContainerId");

                    b.Navigation("DefaultContainer");
                });

            modelBuilder.Entity("ContainerWorkspace", b =>
                {
                    b.HasOne("Andy.Containers.Models.Container", null)
                        .WithMany()
                        .HasForeignKey("ContainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Andy.Containers.Models.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Andy.Containers.Models.Container", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("GitRepositories");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Andy.Containers.Models.Organization", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
